# from .nodes.fal_node import NODE_DISPLAY_NAME_MAPPINGS as FAL_NODE_DISPLAY_NAME_MAPPINGS
# from .nodes.fal_node import NODE_CLASS_MAPPINGS as FAL_NODE_CLASS_MAPPINGS
from .nodes.replicate_node import NODE_DISPLAY_NAME_MAPPINGS as REP_FAL_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.replicate_node import NODE_CLASS_MAPPINGS as REP_FAL_NODE_CLASS_MAPPINGS

NODE_DISPLAY_NAME_MAPPINGS = {
    # **FAL_NODE_DISPLAY_NAME_MAPPINGS,
    **REP_FAL_NODE_DISPLAY_NAME_MAPPINGS
}

NODE_CLASS_MAPPINGS = {
    # **FAL_NODE_CLASS_MAPPINGS,
    **REP_FAL_NODE_CLASS_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

